### ISSUE TITLE
Client Error at times

### ISSUE THREAD

**Issue by joebuonocore** [LukeTowers/oc-azureadsso-plugin#2]
We have this plugin installed on an October application and it works well sometimes--users are able to SSO with their organizational MS accounts and access the application.

At times, the error below is received after the user is redirected to the application and it seems the user was not authenticated.

The odd part on this end is that sometimes users are able to login, sometimes they are not. Any ideas on what may be the issue and/or what we can do to fix?

```
Client error: `POST https://login.microsoftonline.com/common/oauth2/token` resulted in a `400 Bad Request` response: {"error":"interaction_required","error_description":"AADSTS50076: Due to a configuration change made by your administrat (truncated...)
~/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php line 113
```

**Comment by LukeTowers** [comment]
Perhaps https://stackoverflow.com/questions/68160287/microsoft-azure-ad-error-descriptiondue-to-a-configuration-change-made-by-you can help you?

Side note, this plugin will be forked as Winter.SSOAzureAD shortly and build off of the [Winter.SSO](https://github.com/wintercms/wn-sso-plugin) plugin. If you'd like to beta test that, let me know and I'll fork it so you can give it a try. Also let me know if you're using the create user on login functionality or just provide more information about how you use this plugin in general so that I can use that to inform how I refactor it as Winter.SSOAzureAD

**Comment by joebuonocore** [comment]
Thank you @LukeTowers! Item 2 on the linked answer seems to have solved the issue here.

Regarding your side note, I'd be happy to test anything out.

**Comment by LukeTowers** [comment]
@joebuonocore great, will keep you posted.

Let me know if you're using the create user on login functionality or just provide more information about how you use this plugin in general so that I can use that to inform how I refactor it as Winter.SSOAzureAD

**Comment by joebuonocore** [comment]
@LukeTowers We are using the create user on login functionality. We're also auto-assigning a role for the new users in case that seems to be a useful feature to include.

**Comment by LukeTowers** [comment]
@joebuonocore would it be better to simply have this plugin fire an event (like `winter.sso.user.beforeRegister`) when a previously unknown user authenticates via SSO and have your own plugin handle creating that user or would it be better to have a couple config values (something like `winter.sso.create_if_missing`, `winter.sso.default_user_role`, etc?) instead (or do both)?

**Comment by joebuonocore** [comment]
@LukeTowers Either way! I like the event method a little more because it might allow for more flexibility.
